dataset_path: data/dataset/
dataset_name:
  - imagenet
  - mini_imagenet
  - webqa
  - clueweb
dataset_split:
  - train
  - val
  - test
caption_extract_model:
  - llava-v1.6-34b
  - llava-v1.6-mixtral-7b
  - llava-v1.6-mixtral-13b
  - llava-v1.6-vicuna-7b